### ISSUE TITLE
enki does not work with python3

### ISSUE THREAD

**Issue by peterdekker** [PyBossa/enki#22]
enki does not seem to work with python 3. If I try to import enki in a python3 shell, I get the following error
```
>>> import enki
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/enki/__init__.py", line 25, in <module>
    import pbclient
  File "/usr/local/lib/python3.5/dist-packages/pbclient/__init__.py", line 168
    print OFFSET_WARNING
                       ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by teleyinex** [comment]
Yes. We know it. We're planning to start migrating everything to Python 3.5 in the coming months.
